/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTitle: typeof import('./src/components/about/AboutTitle.vue')['default']
    AnchorNavigation: typeof import('./src/components/AnchorNavigation.vue')['default']
    AwardsSection: typeof import('./src/components/AwardsSection.vue')['default']
    BBreadcrumb: typeof import('bootstrap-vue-next/components/BBreadcrumb')['BBreadcrumb']
    BBreadcrumbItem: typeof import('bootstrap-vue-next/components/BBreadcrumb')['BBreadcrumbItem']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BottomBannerSection: typeof import('./src/components/BottomBannerSection.vue')['default']
    Branches: typeof import('./src/components/contact/Branches.vue')['default']
    BrandsSection: typeof import('./src/components/BrandsSection.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    ContactForm: typeof import('./src/components/contact/ContactForm.vue')['default']
    CookieBanner: typeof import('./src/components/CookieBanner.vue')['default']
    CustomSyntax: typeof import('./src/components/CustomSyntax.vue')['default']
    Deliverables: typeof import('./src/components/about/Deliverables.vue')['default']
    ExamplesSection: typeof import('./src/components/ExamplesSection.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    Jarallax: typeof import('./src/components/Jarallax.vue')['default']
    LightGallery: typeof import('./src/components/LightGallery.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    MapSection: typeof import('./src/components/about/MapSection.vue')['default']
    Parallax: typeof import('./src/components/Parallax.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    ProductsSection: typeof import('./src/components/ProductsSection.vue')['default']
    Rellax: typeof import('./src/components/Rellax.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestimonialSection: typeof import('./src/components/about/TestimonialSection.vue')['default']
    TrustedBySection: typeof import('./src/components/TrustedBySection.vue')['default']
    VanillaTilt: typeof import('./src/components/VanillaTilt.vue')['default']
    VideoPopup: typeof import('./src/components/VideoPopup.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
